### Create an array

In [1]:
import numpy as np

In [2]:
np.array([2, 4 , 6, 8])

array([2, 4, 6, 8])

In [3]:
variables = [5.8 , 9, 7, 5]

In [4]:
print(type(variables[0]))     # list can be of any type
print(type(variables[1]))

<class 'float'>
<class 'int'>


In [5]:
new_variable = np.array([5.8 , 9, 7, 5])

In [6]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [7]:
print(type(new_variable[0]))    # array has same type as the first element
print(type(new_variable[1]))

<class 'numpy.float64'>
<class 'numpy.float64'>


In [8]:
new_variable_2 = np.array([5.8 , 9, 7, 5], dtype = int)   # convert to int

In [9]:
new_variable_2

array([5, 9, 7, 5])

### Creating a numpy array with zeros() function

In [10]:
np.zeros(5)   # create an array of zeros

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 5), dtype = int) # create a 3x5 array of zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Creating numpy array with ones() function

In [12]:
np.ones(10)   # create an array of ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((3, 4, 5), dtype=int) # create a 3x4x5 array of ones

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

### Creating numpy array with full() function

In [14]:
np.full(8, 5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [15]:
np.full((2, 3), 6, dtype = int) # create a 2x3 array of 6s

array([[6, 6, 6],
       [6, 6, 6]])

### Creating numpy array with arange() function

syntax: arange(start, stop, step, dtype)

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
example = np.arange(3, 10, dtype=float)

In [18]:
print(example)

[3. 4. 5. 6. 7. 8. 9.]


In [19]:
print(type(example[0]))  # array has same type as the first element

<class 'numpy.float64'>


### Creating numpy array with eye() function

Eye() function allows us to create a unit matrix. 

A unit matrix is a square matrix with ones on the diagonal and zeros elsewhere.

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
np.eye(3, 2, dtype=bool) # create a 3x2 identity matrix of booleans

array([[ True, False],
       [False,  True],
       [False, False]])

### Creating numpy array with linspace() function

In [23]:
np.linspace(10, 30, 10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

### Creating numpy array with random() function

In [24]:
np.random.rand(5)    

array([0.1353201 , 0.23912862, 0.72246112, 0.76028184, 0.57195043])

In [25]:
np.random.rand(2, 3) # create a 2x3 array of random floats between 0 and 1

array([[0.99033401, 0.3357502 , 0.56248987],
       [0.96712566, 0.81555156, 0.19673241]])

In [26]:
np.random.randn(5)   # create a 1D array of random floats from standard normal distribution

array([-0.19708134,  0.15143318, -0.41271585, -0.4980306 , -0.78859955])

In [27]:
np.random.normal(20, 5, (4, 3)) # create a 4x3 array of random floats from normal distribution with mean 20 and std 5

array([[19.84559531, 29.31048523, 25.43671145],
       [18.8571471 , 21.53305872, 23.79161686],
       [14.94586255, 22.31963956, 20.81126063],
       [12.73946936, 23.78389082, 26.45870673]])

In [28]:
np.random.randint(0, 10, (4, 4)) # create a 4x4 array of random integers between 0 and 10

array([[7, 7, 2, 0],
       [8, 1, 7, 4],
       [1, 5, 7, 0],
       [1, 1, 7, 4]])

### Properties of numpy array

ndim: Returns the number of dimensions of the array.

shape: Returns the shape of the array.

size: Returns the total number of elements in the array.

dtype: Returns the data type of the elements in the array.

itemsize: Returns the size (in bytes) of each element in the array.

nbytes: Returns the total number of bytes used by the array.

In [29]:
matrix = np.random.randint(10, 50, (5, 4))

In [30]:
matrix

array([[42, 30, 45, 25],
       [25, 42, 42, 25],
       [28, 45, 35, 41],
       [46, 22, 45, 46],
       [45, 28, 34, 33]])

In [31]:
matrix.ndim

2

In [32]:
matrix.shape

(5, 4)

In [33]:
matrix.size

20

In [34]:
matrix.dtype

dtype('int64')