### reshape() function:

In [1]:
import numpy as np

In [2]:
example  = np.arange(1, 16)

In [3]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
example.reshape((3, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
array = example.reshape((1, 15))

In [6]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
example.ndim

1

In [8]:
array.ndim

2

In [9]:
example.reshape((4, 3)) # cant shape 15 into 12 elements

ValueError: cannot reshape array of size 15 into shape (4,3)

### argmax() function:

In [10]:
array = np.random.randint(0, 50, 10)

In [11]:
array.max()

46

In [12]:
array.argmax()    # position of max value

1

In [13]:
array

array([38, 46,  5,  4, 42, 15, 40, 34, 22,  7])

In [14]:
array2 = np.random.randint(0, 50, (4, 3))

In [15]:
array2

array([[42, 33, 11],
       [ 1, 48, 20],
       [31, 12, 43],
       [44, 19, 35]])

In [16]:
array2.max()

48

In [17]:
array2.argmax()

4

### argmin() function:

In [18]:
array3 = np.random.randint(20, 70, 10)

In [19]:
array3

array([58, 54, 29, 26, 32, 42, 23, 37, 50, 67])

In [20]:
array3.min()

23

In [21]:
array3.argmin()

6

In [22]:
array4 = np.random.randint(20, 70, (5, 3))

In [23]:
array4

array([[33, 25, 42],
       [32, 67, 20],
       [23, 47, 48],
       [26, 57, 63],
       [60, 27, 40]])

In [24]:
array4.min()

20

In [25]:
array4.argmin()

5

### Concatenate() function:

In [26]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [27]:
np.concatenate((array1, array2)) # concatenate 1D arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
array3 = np.arange(1, 7).reshape((2, 3))

In [29]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array4 = np.array([[7, 8, 9], [10, 11, 12]])

In [31]:
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([array3, array4]) # concatenate 2D arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate([array3, array4], axis=1) # concatenate 2D arrays along columns

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.concatenate([array1, array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [36]:
array5 = np.arange(1, 11).reshape((5, 2))

In [37]:
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
np.concatenate([array3, array5])   # cant concatenate 2D and 1D arrays

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2