### reshape() function:

In [1]:
import numpy as np

In [2]:
example  = np.arange(1, 16)

In [3]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
example.reshape((3, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
array = example.reshape((1, 15))

In [6]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
example.ndim

1

In [8]:
array.ndim

2

In [10]:
example.reshape((4, 3)) # cant shape 15 into 12 elements

ValueError: cannot reshape array of size 15 into shape (4,3)

### argmax() function:

In [12]:
array = np.random.randint(0, 50, 10)

In [13]:
array.max()

48

In [ ]:
array.argmax()    # position of max value

0

In [15]:
array

array([48,  0,  5, 19,  0, 31, 38, 29, 17, 43])

In [16]:
array2 = np.random.randint(0, 50, (4, 3))

In [17]:
array2

array([[38,  5, 32],
       [41, 47, 10],
       [40, 38,  4],
       [ 3, 41, 36]])

In [18]:
array2.max()

47

In [20]:
array2.argmax()

4

### argmin() function:

In [22]:
array3 = np.random.randint(20, 70, 10)

In [23]:
array3

array([46, 37, 66, 65, 66, 57, 49, 44, 27, 31])

In [24]:
array3.min()

27

In [26]:
array3.argmin()

8

In [27]:
array4 = np.random.randint(20, 70, (5, 3))

In [28]:
array4

array([[25, 69, 48],
       [60, 40, 60],
       [29, 59, 21],
       [46, 62, 32],
       [41, 48, 48]])

In [29]:
array4.min()

21

In [30]:
array4.argmin()

8