### reshape() function:

In [1]:
import numpy as np

In [2]:
example  = np.arange(1, 16)

In [3]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
example.reshape((3, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
array = example.reshape((1, 15))

In [6]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
example.ndim

1

In [8]:
array.ndim

2

In [9]:
example.reshape((4, 3)) # cant shape 15 into 12 elements

ValueError: cannot reshape array of size 15 into shape (4,3)

### argmax() function:

In [10]:
array = np.random.randint(0, 50, 10)

In [11]:
array.max()

46

In [12]:
array.argmax()    # position of max value

1

In [13]:
array

array([38, 46,  5,  4, 42, 15, 40, 34, 22,  7])

In [14]:
array2 = np.random.randint(0, 50, (4, 3))

In [15]:
array2

array([[42, 33, 11],
       [ 1, 48, 20],
       [31, 12, 43],
       [44, 19, 35]])

In [16]:
array2.max()

48

In [17]:
array2.argmax()

4

### argmin() function:

In [18]:
array3 = np.random.randint(20, 70, 10)

In [19]:
array3

array([58, 54, 29, 26, 32, 42, 23, 37, 50, 67])

In [20]:
array3.min()

23

In [21]:
array3.argmin()

6

In [22]:
array4 = np.random.randint(20, 70, (5, 3))

In [23]:
array4

array([[33, 25, 42],
       [32, 67, 20],
       [23, 47, 48],
       [26, 57, 63],
       [60, 27, 40]])

In [24]:
array4.min()

20

In [25]:
array4.argmin()

5

### Concatenate() function:

In [26]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [27]:
np.concatenate((array1, array2)) # concatenate 1D arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
array3 = np.arange(1, 7).reshape((2, 3))

In [29]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array4 = np.array([[7, 8, 9], [10, 11, 12]])

In [31]:
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([array3, array4]) # concatenate 2D arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate([array3, array4], axis=1) # concatenate 2D arrays along columns

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.concatenate([array1, array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [36]:
array5 = np.arange(1, 11).reshape((5, 2))

In [37]:
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
np.concatenate([array3, array5])   # cant concatenate 2D and 1D arrays

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

### Splitting one-dimesional arrays:

In [40]:
array = np.array([1,3,5,50,50,2,4,6])

In [41]:
np.split(array, [3, 5]) # split array into 3 parts at index 3 and 5

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [42]:
x, y, z = np.split(array, [3, 5]) # unpack the split arrays

In [43]:
x

array([1, 3, 5])

In [44]:
y

array([50, 50])

In [45]:
z

array([2, 4, 6])

In [47]:
np.split(array, 4) # split into 4 equal parts

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [48]:
np.split(array, 5) # split into 5 equal parts

ValueError: array split does not result in an equal division

### Splitting two-dimesional arrays:

In [49]:
array = np.arange(20).reshape(5, 4)

In [50]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
np.split(array, [1, 3]) # split 2D array into 3 parts at index 1 and 3

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [52]:
x , y, z = np.split(array, [1, 3]) # unpack the split arrays

In [53]:
x

array([[0, 1, 2, 3]])

In [54]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
np.split(array, [1, 3], axis=1) # split 2D array into 3 parts at index 1 and 3 along columns

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

### hsplit function:

In [58]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
np.hsplit(array, 4) # split 2D array into 4 equal parts along columns

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [60]:
np.hsplit(array, [1, 3]) # split 2D array into 3 parts at index 1 and 3 along columns

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

### vsplit function:

In [61]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
np.vsplit(array, 5) # split 2D array into 5 equal parts along rows

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [64]:
np.vsplit(array, [2, 4]) # split 2D array into 3 parts at index 2 and 4 along rows

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

### sort() function:

In [67]:
variable = np.array([3,5,1,8,6,2,9])

In [68]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [69]:
np.sort(variable) # sort the array in ascending order

array([1, 2, 3, 5, 6, 8, 9])

In [70]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [71]:
variable2 = np.sort(variable) # sort the array in ascending order and assign to a new variable

In [72]:
variable2

array([1, 2, 3, 5, 6, 8, 9])

In [73]:
example = np.random.normal(30, 10, (4, 4))

In [74]:
example

array([[35.11096108, 25.48627747, 46.3801061 , 31.23403985],
       [35.60070955, 15.70173294, 11.4632385 , 25.14825741],
       [29.72616524, 26.95767204, 29.9574978 , 31.16288649],
       [19.58915844, 28.68824863, 28.70896836, 22.7534081 ]])

In [75]:
np.sort(example, axis=0) # sort the 2D array along columns

array([[19.58915844, 15.70173294, 11.4632385 , 22.7534081 ],
       [29.72616524, 25.48627747, 28.70896836, 25.14825741],
       [35.11096108, 26.95767204, 29.9574978 , 31.16288649],
       [35.60070955, 28.68824863, 46.3801061 , 31.23403985]])

In [76]:
np.sort(example, axis=1) # sort the 2D array along rows

array([[25.48627747, 31.23403985, 35.11096108, 46.3801061 ],
       [11.4632385 , 15.70173294, 25.14825741, 35.60070955],
       [26.95767204, 29.72616524, 29.9574978 , 31.16288649],
       [19.58915844, 22.7534081 , 28.68824863, 28.70896836]])